[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  Nqueue = "false"
  # Blob storage feature flags
  USE_BLOB_STORAGE = "true"  # Set to "true" to enable blob storage
  BLOB_FALLBACK_ENABLED = "true"  # Always keep fallbacks enabled

[dev]
  targetPort = 3000
  port = 8888
  framework = "create-react-app"

# Ignore builds when only data files change
[build.processing]
  skip_processing = false

# Build ignore command to prevent rebuilds on data-only changes
[build.processing.html]
  pretty_urls = true

# Cache static assets for 1 year
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses for 5 minutes
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' ws://localhost:3000 ws://localhost:8888; worker-src 'self' blob:; child-src 'self' blob:;" 