name: EA Batch 5 (H-L, 94 stations)

on:
  schedule:
    - cron: '10 2,8,14,20 * * *'  # Every 6 hours at 02:10, 08:10, 14:10, 20:10
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  ea-batch-5:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run EA batch 5 scraping script
      env:
        EA_BATCH_NUM: 5
        EA_BATCH_START: "Hexham Firtrees"
        EA_BATCH_END: "Longcliffe"
      run: node scripts/download-ea-batch.js
    
    - name: Upload to Netlify Blobs
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        EA_BATCH_NUM: 5
        EA_BATCH_START: "Hexham Firtrees"
        EA_BATCH_END: "Longcliffe"
      run: node scripts/github-actions-blob-upload.js
    
    
    - name: Summary
      run: |
        echo "## EA Batch 5 Data Update Complete" >> $GITHUB_STEP_SUMMARY
        echo "- **Range**: Hexham Firtrees → Longcliffe" >> $GITHUB_STEP_SUMMARY
        echo "- **Letters**: H-L" >> $GITHUB_STEP_SUMMARY
        echo "- **Stations**: 94 EA stations" >> $GITHUB_STEP_SUMMARY
        echo "- Data scraped and processed" >> $GITHUB_STEP_SUMMARY
        echo "- Uploaded to Netlify Blobs" >> $GITHUB_STEP_SUMMARY
        echo "- **Data Storage**: Netlify Blobs (Primary)" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ✅ Data successfully uploaded to blobs" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "_Note: Data is stored in Netlify Blobs only (no git commits)_" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
    
    - name: Handle errors
      if: failure()
      run: |
        echo "## EA Batch 5 Update Failed" >> $GITHUB_STEP_SUMMARY
        echo "- **Range**: Hexham Firtrees → Longcliffe" >> $GITHUB_STEP_SUMMARY
        echo "- **Stations**: 94 EA stations" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Action**: Check logs for details" >> $GITHUB_STEP_SUMMARY
        echo "- **Fallback**: Previous data still available in Netlify Blobs" >> $GITHUB_STEP_SUMMARY
