name: EA Multi-Stations (10 Stations)

on:
  schedule:
    - cron: '45 */6 * * *'  # Every 6 hours at 45 minutes past
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  ea-multi-stations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run EA multi-stations scraping script
      run: node scripts/download-ea-multi-stations.js
    
    - name: Upload to Netlify Blobs
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: node scripts/github-actions-blob-upload.js
    
    - name: Summary
      run: |
        echo "## EA Multi-Stations Data Update Complete" >> $GITHUB_STEP_SUMMARY
        echo "- **Stations**: 10 EA stations across UK regions" >> $GITHUB_STEP_SUMMARY
        echo "- **Regions**: East Midlands, South East, South West, North West, Yorkshire, North East, West Midlands" >> $GITHUB_STEP_SUMMARY
        echo "- **Data Storage**: Netlify Blobs (Primary)" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ✅ Data successfully uploaded to blobs" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "_Note: Data is stored in Netlify Blobs only (no git commits)_" >> $GITHUB_STEP_SUMMARY
    
    - name: Handle errors
      if: failure()
      run: |
        echo "## EA Multi-Stations Update Failed" >> $GITHUB_STEP_SUMMARY
        echo "- **Stations**: 10 EA stations" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Action**: Check logs for details" >> $GITHUB_STEP_SUMMARY
        echo "- **Fallback**: Previous data still available in Netlify Blobs" >> $GITHUB_STEP_SUMMARY
